### ISSUE TITLE
Sugestão: human vs bot

### ISSUE THREAD

**Issue by Mazuh** [SampDev/Pedra-Papel-Tesoura#1]
Minha sugestão: coloque pra o humano escolher a opção dele. Da forma como está, tá tipo BOT vs BOT (uma modalidade comum em jogos de luta, por exemplo, mas não é o "tchan") quando o desejado (imagino) seja BOT vs HUMAN.

Alguns jogos implementam essa brincadeira como mini-game como os inícios de duelo do Yu-Gi-Oh GX Tag Force em que você (o humano) escolhe entre pedra, papel e tesoura e o bot faz a escolha dele, para então quem ganhar decidir quem inicia a primeira jogada. Recomendo uma olhada no YouTube se nunca jogou, atentando só pra esse "minigame".

PS: reforçando o comentário lá no Fb... ficou muito simples e bonito o negócio.

**Comment by SampDev** [comment]
Muito obrigado pela issue.. Acabei de implementar tudo isso que você citou, se quiser dar uma olhada basta acessar: https://esprating.ml/pedra-papel-tesoura
