### ISSUE TITLE
Remover "dependência" do PHP

### ISSUE THREAD

**Issue by Mazuh** [SampDev/Pedra-Papel-Tesoura#2]
Não vi o PHP sendo realmente usando em nenhum lugar do código inteiro. Você podia simplesmente renomear a extensão pra ```.html``` e não precisar de servidor nenhum. Assim, fica fácil qualquer um baixar/clonar o repositório e rodar na própria máquina sem piscar.

Se o problema for configurar hospedagem pra disponibilizar o jogo online (talvez o servidor precise de um ```index``` com extensão do PHP obrigatoriamente? não sei), então não há absolutamente nenhuma razão pra se preocupar, porque o próprio Github te ajuda com isso. Pesquise sobre a função do [Github PROJECT Pages](https://help.github.com/articles/user-organization-and-project-pages/). Creio que o maior esforço que você terá é renomear o arquivo no repositório e permitir que o GIthub gere o domínio a partir do index nas configurações do repo -- ou seja, no big deal.

**Comment by SampDev** [comment]
Foi burrice minha mesmo, já atualizei no último commit!

**Comment by Mazuh** [comment]
@SampDev, só faltou ativar o [Github **Project** Pages](https://help.github.com/articles/user-organization-and-project-pages/).

E código do [domínio sugerido por você](https://esprating.ml/pedra-papel-tesoura) não não tá funcionando corretamente. Os botões não funcionam e as imagens renderizadas tẽm atributos ```src='/images/proibido.png'```. Não abri outra issue porque não parece ser um problema de infraestrutura não relacionado ao repositório.

**Comment by SampDev** [comment]
Cara, quando eu dei o commit tava funcionando normal. Deve ter sido quando mudei a extensão do index mesmo. Vou arrumar, é pq fui dormir. Eu vou dar uma olhada em como funciona o GitHub Pages
